spring:
  profiles:
    active: e2e
  jackson:
    deserialization:
      ACCEPT_FLOAT_AS_INT: false

---
spring:
  config:
    activate:
      on-profile: e2e
erp:
  url: http://erp-api:3000
tax:
  url: http://tax-api:3001

---
spring:
  config:
    activate:
      on-profile: qa
erp:
  url: http://erp-api:3000
tax:
  url: http://tax-api:3001

---
spring:
  config:
    activate:
      on-profile: prod
erp:
  url: http://erp-api:3000
tax:
  url: http://tax-api:3001
