services:

  erp-api:
    image: williamyeh/json-server
    ports:
      - "3000:3000"
    volumes:
      - ./json-server-db.erp-api.json:/data/db.json
    command: --watch /data/db.json --host 0.0.0.0

  tax-api:
    image: williamyeh/json-server
    ports:
      - "3001:3001"
    volumes:
      - ./json-server-db.tax-api.json:/data/db.json
    command: --watch /data/db.json --host 0.0.0.0 --port 3001

  monolith:
    image: ghcr.io/optivem/acceptance-testing-in-legacy-code-java/monolith:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=e2e
    depends_on:
      - erp-api
      - tax-api

